# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Analysis-Listener-HTTPClientPerf
version:      0.01
version_from: lib/Net/Analysis/Listener/HTTPClientPerf.pm
installdirs:  site
requires:
    Net::Analysis:                 0.01
    PostScript::Simple:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
